---
# tasks file for hyclak.elasticsearch
- name: '(RedHat) Install'
  when: ansible_os_family == 'RedHat'
  include: RedHat.yml

- name: Configure Elasticsearch
  template:
    src: etc/elasticsearch/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: 0644

- name: Starting Elasticsearch
  service: 
    name: elasticsearch
    state: started
    enabled: yes
